### ISSUE TITLE
Leave blank lines tf alone

### ISSUE THREAD

**Issue by Proliecan** [darmiel/sapui5-helper#1]
## To help the user structure their project
Some users (like myself) structure their XML-files using blank lines to be able   
to quickly get an overview on what's going on when reading the file.

**Those lines currently get removed** by the XML-formatter (s5 fx)  
and it would be nice, if it would keep them.

**Comment by darmiel** [comment]
Added in commit 3ea674c2f6703daa2fc265b4ed2beb97ff81c3ff * with flag `remove-empty-lines`. If empty lines are to be deleted, the `-L` flag can be used:

**without `fx -L`**
```xml
 1  <mvc:View xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" controllerName="crocodile.controller.CrocCalc" displayBlock="true">
 2  <sap.ui.layout:VerticalLayout xmlns:sap.ui.layout="sap.ui.layout" width="100%" id="layout0">
 3  <sap.ui.layout:content>
 4  
 5    <!-- TODO: Add contents here -->
 6  
 7    <Label text="Hello World!" width="100%" id="label0" />
 8  
 9    <test>
10      <test2>
11        <test3 attr="cde" />
12      </test2>
13  
14      <test3>
15        <test6></test6>
16      </test3>
17    </test>
18  
19  </sap.ui.layout:content>
```

**with `fx -L`**
```xml
 1  <mvc:View xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" controllerName="crocodile.controller.CrocCalc" displayBlock="true">
 2  <sap.ui.layout:VerticalLayout xmlns:sap.ui.layout="sap.ui.layout" width="100%" id="layout0">
 3  <sap.ui.layout:content>
 4    <!-- TODO: Add contents here -->
 5    <Label text="Hello World!" width="100%" id="label0" />
 6    <test>
 7      <test2>
 8        <test3 attr="cde" />
 9      </test2>
10      <test3>
11        <test6></test6>
12      </test3>
13    </test>
14  </sap.ui.layout:content>
```

*) related: https://github.com/darmiel/gohtml/commit/5aeb40ffae72a1c5f87346785c9308d89f2f169c, https://github.com/darmiel/net/commit/a08ab7ad97399c5f0c35504c523e5730ea49a968
